const CULTURE_EVENT_TYPES = [
  { value: "panel", label: "Panel" },
  { value: "konser", label: "Konser" },
  { value: "koro", label: "Koro" },
  { value: "tiyatro", label: "Tiyatro" },
  { value: "cocukoyunu", label: "Çocuk Oyunu" },
  { value: "standup", label: "Stand-up" },
  { value: "seminer", label: "Seminer" },
  { value: "muzikal", label: "Müzikal" },
  { value: "dinleti", label: "Dinleti" },
  { value: "yilsonu", label: "Yıl Sonu Gösterisi" },
  { value: "filmGosterimi", label: "Film Gösterimi" },
  { value: "other", label: "Diğer" },
];

export const APP_CONSTANTS = {
  WEEKDAYS: ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"],
  MONTH_NAMES: [
    "Ocak",
    "Şubat",
    "Mart",
    "Nisan",
    "Mayıs",
    "Haziran",
    "Temmuz",
    "Ağustos",
    "Eylül",
    "Ekim",
    "Kasım",
    "Aralık",
  ],
  EVENING_HOUR_THRESHOLD: 18, // 18:00 (6 PM) akşam başlangıcı
  DEFAULT_START_TIME: "12:00",
  DEFAULT_END_TIME: "18:00",
  CURRENT_YEAR: new Date().getFullYear(),
  CURRENT_MONTH: new Date().getMonth(),
  EVENT_TYPES: [
    { value: "wedding", label: "Düğün" },
    { value: "engagement", label: "Nişan" },
    { value: "nikah", label: "Nikah" },
    { value: "breakfast", label: "Kahvaltı" },
    { value: "meeting", label: "Toplantı" },
    { value: "henna", label: "Kına" },
    { value: "circumcision", label: "Sünnet" },
    { value: "other", label: "Diğer" },
    ...CULTURE_EVENT_TYPES,
  ],
  CULTURE_EVENT_TYPES,
  STATUS_OPTIONS: [
    { value: "preliminary", label: "Ön Rezervasyon" },
    { value: "cancelled", label: "İptal Edildi" },
  ],
  CURRENCY_SYMBOL: "₺",
};
